
-- Generated by ORDS REST Data Services 20.3.1.r3321735
-- Schema: DEV  Date: Thu Jan 07 12:56:40 2021 
--

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'DEV',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'lms',
      p_auto_rest_auth      => TRUE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'ORACLE.PKG',
      p_base_path      => '/pkg/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ORACLE.PKG',
      p_pattern        => 'author_genres/genres/:a_id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ORACLE.PKG',
      p_pattern        => 'author_genres/genres/:a_id',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => 'Retrieve all genres for a author specified by a_id',
      p_source         => 
'SELECT g_id FROM genres g NATURAL JOIN author_genres
WHERE a_id = :a_id order by g_id');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ORACLE.PKG',
      p_pattern        => 'book_author_publishes/authors/:bk_id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ORACLE.PKG',
      p_pattern        => 'book_author_publishes/authors/:bk_id',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => 'Retrieve all authors for a book specified by bk_id',
      p_source         => 
'select a_id from authors a
natural join book_author_publishes
where bk_id = :bk_id order by a_id
    ');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ORACLE.PKG',
      p_pattern        => 'book_author_publishes',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ORACLE.PKG',
      p_pattern        => 'book_author_publishes',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => 'Retrieve all books and their authors in form of each individual set.',
      p_source         => 
'select * from books b
INNER JOIN book_author_publishes bap ON bap.bk_id = b.bk_id 
INNER JOIN authors a ON a.a_id = bap.a_id
    ');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ORACLE.PKG',
      p_pattern        => 'member_preferences/genres/:m_id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ORACLE.PKG',
      p_pattern        => 'member_preferences/genres/:m_id',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => 'Retrieve all genre preferences of a member specified by m_id',
      p_source         => 
'SELECT g_id FROM genres g
NATURAL JOIN member_preferences
where m_id = :m_id order by g_id
    ');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ORACLE.PKG',
      p_pattern        => 'member_preferences',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ORACLE.PKG',
      p_pattern        => 'member_preferences',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => 'Retrieve members preferences each in form of a different set',
      p_source         => 
'select * from members m
INNER JOIN member_preferences mp ON mp.m_id = m.m_id 
INNER JOIN genres g ON g.g_id = mp.g_id order by m.m_id
    ');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ORACLE.PKG',
      p_pattern        => 'book_copies/:bk_id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ORACLE.PKG',
      p_pattern        => 'book_copies/:bk_id',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => 'Retrieve all copies of a book specified by bk_id',
      p_source         => 
'select copy_id, bk_id from book_copies where bk_id = :bk_id');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ORACLE.PKG',
      p_pattern        => 'book_genres/books/:g_id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ORACLE.PKG',
      p_pattern        => 'book_genres/books/:g_id',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => 'Retrieves all books for a genre specified by g_id',
      p_source         => 
'SELECT bk_id FROM books b NATURAL JOIN book_genres
WHERE g_id = :g_id order by bk_id');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ORACLE.PKG',
      p_pattern        => 'book_genres/genres/:bk_id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ORACLE.PKG',
      p_pattern        => 'book_genres/genres/:bk_id',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => 'Retrieve all genres of a book specified by bk_id',
      p_source         => 
'SELECT g_id FROM genres g NATURAL JOIN book_genres
WHERE bk_id = :bk_id order by g_id');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ORACLE.PKG',
      p_pattern        => 'author_genres/authors/:g_id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ORACLE.PKG',
      p_pattern        => 'author_genres/authors/:g_id',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => 'Retrieve all authors for a genre specified by g_id',
      p_source         => 
'SELECT a_id FROM authors a NATURAL JOIN author_genres
WHERE g_id = :g_id order by a_id');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ORACLE.PKG',
      p_pattern        => 'book_author_publishes/books/:a_id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ORACLE.PKG',
      p_pattern        => 'book_author_publishes/books/:a_id',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => 'Retrieve all books for an author specified by a_id',
      p_source         => 
'select bk_id from books
natural join book_author_publishes
where a_id = :a_id order by bk_published_date DESC
    ');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ORACLE.PKG',
      p_pattern        => 'author_reviews/authors/:m_id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ORACLE.PKG',
      p_pattern        => 'author_reviews/authors/:m_id',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => 'Retrieve all author reviews by a member specified by m_id',
      p_source         => 
'SELECT r_text, r_rating, to_char(r_date,''DD-MM-YYYY'') as r_date, a_id, a_first_name, a_last_name, a_image_url FROM authors
NATURAL JOIN author_reviews
where m_id = :m_id order by r_date DESC');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ORACLE.PKG',
      p_pattern        => 'book_copies_issues/bk_id/:bk_id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ORACLE.PKG',
      p_pattern        => 'book_copies_issues/bk_id/:bk_id',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => 'Retrieve data about issues by members for a copy of a book specified by bk_id',
      p_source         => 
'SELECT issue_id, m_id, m_first_name, m_last_name,
m_image_url,
issue_date, 
due_date, 
returned_date
FROM BOOK_COPIES_ISSUES bci
NATURAL JOIN MEMBERS
WHERE bk_id = :bk_id
ORDER BY bci.issue_date DESC');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ORACLE.PKG',
      p_pattern        => 'book_reviews/members/:bk_id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ORACLE.PKG',
      p_pattern        => 'book_reviews/members/:bk_id',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => 'Retrieve all member reviews for a book specified by bk_id',
      p_source         => 
'SELECT r_text, r_rating, to_char(r_date,''DD-MM-YYYY'') as r_date, m_id, m_first_name, m_last_name, m_image_url FROM members
NATURAL JOIN book_reviews
where bk_id = :bk_id order by r_date DESC');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ORACLE.PKG',
      p_pattern        => 'book_copies_issues/m_id/:m_id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ORACLE.PKG',
      p_pattern        => 'book_copies_issues/m_id/:m_id',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => 'Retrieve data about all book issues by a member specified by m_id',
      p_source         => 
'SELECT issue_id, copy_id, bk_id, m_id, bk_name, bk_image_url, (a_first_name || '' '' || a_last_name) as a_name, issue_date, due_date, returned_date
FROM BOOK_COPIES_ISSUES bci
NATURAL JOIN BOOK_COPIES
NATURAL JOIN BOOKS
NATURAL JOIN BOOK_AUTHOR_PUBLISHES
NATURAL JOIN AUTHORS
WHERE m_id = :m_id ORDER BY bci.issue_date');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ORACLE.PKG',
      p_pattern        => 'member_preferences/members/:g_id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ORACLE.PKG',
      p_pattern        => 'member_preferences/members/:g_id',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => 'Retrieve all members with a genre preferences specified by g_id',
      p_source         => 
'SELECT m_id FROM members
NATURAL JOIN member_preferences
where g_id = :g_id order by m_id');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ORACLE.PKG',
      p_pattern        => 'author_reviews/members/:a_id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ORACLE.PKG',
      p_pattern        => 'author_reviews/members/:a_id',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => 'Retrieve all member reviews for an author specified by a_id',
      p_source         => 
'SELECT r_text, r_rating, to_char(r_date,''DD-MM-YYYY'') as r_date, m_id, m_first_name, m_last_name, m_image_url FROM members
NATURAL JOIN author_reviews
where a_id = :a_id order by r_date DESC');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ORACLE.PKG',
      p_pattern        => 'book_reviews/books/:m_id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ORACLE.PKG',
      p_pattern        => 'book_reviews/books/:m_id',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => 'Retrieve all book reviews by a member specified by m_id',
      p_source         => 
'SELECT r_text, r_rating, to_char(r_date,''DD-MM-YYYY'') as r_date, bk_id, bk_name, bk_rating, bk_image_url FROM books
NATURAL JOIN book_reviews
where m_id = :m_id order by r_date DESC
    ');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ORACLE.PKG',
      p_pattern        => 'book_top_5_rated/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ORACLE.PKG',
      p_pattern        => 'book_top_5_rated/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select bk_id from (select * from books order by bk_rating DESC) t where rownum<=5');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ORACLE.PKG',
      p_pattern        => 'book_new_5_collection/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ORACLE.PKG',
      p_pattern        => 'book_new_5_collection/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select bk_id from (select * from books order by bk_published_date desc) t where rownum<=5');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'ORACLE.PKG',
      p_pattern        => 'book_copies_issues/copy_id/:copy_id',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => 'Returns true/false depending on a copy''s availability for borrowing');

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'ORACLE.PKG',
      p_pattern        => 'book_copies_issues/copy_id/:copy_id',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => '',
      p_comments       => 'Returns the count of issues that aren''t returned for the specified copy_id.',
      p_source         => 
'SELECT COUNT(*) count_issues
FROM BOOK_COPIES_ISSUES bci
WHERE copy_id = :copy_id AND returned_date IS NULL');

    
        
COMMIT;

END;