CREATE TABLE  "BOOKS" 
   (	"BK_ID" NUMBER NOT NULL ENABLE, 
	"BK_NAME" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"BK_RATING" NUMBER NOT NULL ENABLE, 
	"BK_BIO" NVARCHAR2(2000) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"BK_IMAGE_URL" VARCHAR2(2000) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"BK_PUBLISHED_DATE" DATE NOT NULL ENABLE, 
	 CONSTRAINT "BOOKS_PK" PRIMARY KEY ("BK_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "BK_RATING_LIMIT" CHECK ("BK_RATING" BETWEEN 0 AND 5) ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
CREATE TABLE  "BOOK_COPIES" 
   (	"COPY_ID" NUMBER NOT NULL ENABLE, 
	"BK_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "COPIES_PK" PRIMARY KEY ("COPY_ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
CREATE TABLE  "MEMBERS" 
   (	"M_ID" NUMBER NOT NULL ENABLE, 
	"M_FIRST_NAME" VARCHAR2(30) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"M_LAST_NAME" VARCHAR2(30) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"M_BIO" NVARCHAR2(2000) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"M_START_DATE" DATE NOT NULL ENABLE, 
	"M_AGE" NUMBER NOT NULL ENABLE, 
	"M_IMAGE_URL" VARCHAR2(2000) COLLATE "USING_NLS_COMP", 
	"M_EMAIL" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"M_PASSWORD" VARCHAR2(8) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	 CONSTRAINT "MEMBERS_PK" PRIMARY KEY ("M_ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
CREATE TABLE  "BOOK_REVIEWS" 
   (	"R_RATING" NUMBER NOT NULL ENABLE, 
	"R_TEXT" VARCHAR2(4000) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"R_DATE" DATE NOT NULL ENABLE, 
	"BK_ID" NUMBER NOT NULL ENABLE, 
	"M_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "BR_PK" PRIMARY KEY ("BK_ID", "M_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "BKR_RATING_LIMIT" CHECK ("R_RATING" BETWEEN 0 AND 5) ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
CREATE TABLE  "GENRES" 
   (	"G_ID" NUMBER DEFAULT  "GENRES_SEQUENCE"."NEXTVAL" NOT NULL ENABLE, 
	"G_NAME" VARCHAR2(4000) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	 CONSTRAINT "GENRES_PK" PRIMARY KEY ("G_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "UNIQUE_G_NAME" UNIQUE ("G_NAME")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
CREATE TABLE  "BOOK_GENRES" 
   (	"BK_ID" NUMBER NOT NULL ENABLE, 
	"G_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "BG_PK" PRIMARY KEY ("BK_ID", "G_ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
CREATE TABLE  "AUTHORS" 
   (	"A_ID" NUMBER NOT NULL ENABLE, 
	"A_FIRST_NAME" VARCHAR2(30) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"A_LAST_NAME" VARCHAR2(30) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"A_AGE" NUMBER NOT NULL ENABLE, 
	"A_COUNTRY" CHAR(3) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"A_RATING" NUMBER NOT NULL ENABLE, 
	"A_IMAGE_URL" VARCHAR2(2000) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	 CONSTRAINT "AUTHORS_PK" PRIMARY KEY ("A_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "RATING_LIMIT" CHECK ("A_RATING" BETWEEN 0 AND 5) ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
CREATE TABLE  "BOOK_AUTHOR_PUBLISHES" 
   (	"BK_ID" NUMBER NOT NULL ENABLE, 
	"A_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "BAP_PK" PRIMARY KEY ("BK_ID", "A_ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
CREATE TABLE  "AUTHOR_REVIEWS" 
   (	"R_RATING" NUMBER NOT NULL ENABLE, 
	"R_TEXT" VARCHAR2(4000) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"R_DATE" DATE NOT NULL ENABLE, 
	"A_ID" NUMBER NOT NULL ENABLE, 
	"M_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "AR_PK" PRIMARY KEY ("A_ID", "M_ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "AR_RATING_LIMIT" CHECK ("R_RATING" BETWEEN 0 AND 5) ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
CREATE TABLE  "AUTHOR_GENRES" 
   (	"A_ID" NUMBER NOT NULL ENABLE, 
	"G_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "AG_PK" PRIMARY KEY ("A_ID", "G_ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
CREATE TABLE  "MEMBER_PREFERENCES" 
   (	"M_ID" NUMBER NOT NULL ENABLE, 
	"G_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "MP_PK" PRIMARY KEY ("M_ID", "G_ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
CREATE TABLE  "BOOK_COPIES_ISSUES" 
   (	"ISSUE_ID" NUMBER NOT NULL ENABLE, 
	"ISSUE_DATE" DATE NOT NULL ENABLE, 
	"DUE_DATE" DATE NOT NULL ENABLE, 
	"RETURNED_DATE" DATE, 
	"COPY_ID" NUMBER NOT NULL ENABLE, 
	"M_ID" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "BOOK_COPIES_ISSUES_PK" PRIMARY KEY ("ISSUE_ID", "COPY_ID", "M_ID")
  USING INDEX  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"
/
ALTER TABLE  "BOOK_COPIES" ADD CONSTRAINT "FK_BC_BK_ID" FOREIGN KEY ("BK_ID")
	  REFERENCES  "BOOKS" ("BK_ID") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "BOOK_GENRES" ADD CONSTRAINT "FK_BG_BK_ID" FOREIGN KEY ("BK_ID")
	  REFERENCES  "BOOKS" ("BK_ID") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "BOOK_GENRES" ADD CONSTRAINT "FK_BG_G_ID" FOREIGN KEY ("G_ID")
	  REFERENCES  "GENRES" ("G_ID") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "AUTHOR_GENRES" ADD CONSTRAINT "FK_AG_G_ID" FOREIGN KEY ("G_ID")
	  REFERENCES  "GENRES" ("G_ID") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "AUTHOR_GENRES" ADD CONSTRAINT "FK_AG_A_ID" FOREIGN KEY ("A_ID")
	  REFERENCES  "AUTHORS" ("A_ID") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "MEMBER_PREFERENCES" ADD CONSTRAINT "FK_MP_G_ID" FOREIGN KEY ("G_ID")
	  REFERENCES  "GENRES" ("G_ID") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "MEMBER_PREFERENCES" ADD CONSTRAINT "FK_MP_M_ID" FOREIGN KEY ("M_ID")
	  REFERENCES  "MEMBERS" ("M_ID") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "BOOK_REVIEWS" ADD CONSTRAINT "FK_BR_M_ID" FOREIGN KEY ("M_ID")
	  REFERENCES  "MEMBERS" ("M_ID") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "BOOK_REVIEWS" ADD CONSTRAINT "FK_BR_BK_ID" FOREIGN KEY ("BK_ID")
	  REFERENCES  "BOOKS" ("BK_ID") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "AUTHOR_REVIEWS" ADD CONSTRAINT "FK_AR_M_ID" FOREIGN KEY ("M_ID")
	  REFERENCES  "MEMBERS" ("M_ID") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "AUTHOR_REVIEWS" ADD CONSTRAINT "FK_AR_A_ID" FOREIGN KEY ("A_ID")
	  REFERENCES  "AUTHORS" ("A_ID") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "BOOK_COPIES_ISSUES" ADD CONSTRAINT "FK_BCI_COPY_ID" FOREIGN KEY ("COPY_ID")
	  REFERENCES  "BOOK_COPIES" ("COPY_ID") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "BOOK_COPIES_ISSUES" ADD CONSTRAINT "FK_BCI_M_ID" FOREIGN KEY ("M_ID")
	  REFERENCES  "MEMBERS" ("M_ID") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "BOOK_AUTHOR_PUBLISHES" ADD CONSTRAINT "FK_BAP_A_ID" FOREIGN KEY ("A_ID")
	  REFERENCES  "AUTHORS" ("A_ID") ON DELETE CASCADE ENABLE
/
ALTER TABLE  "BOOK_AUTHOR_PUBLISHES" ADD CONSTRAINT "FK_BAP_BK_ID" FOREIGN KEY ("BK_ID")
	  REFERENCES  "BOOKS" ("BK_ID") ON DELETE CASCADE ENABLE
/
CREATE UNIQUE INDEX  "BOOKS_PK" ON  "BOOKS" ("BK_ID")
/
CREATE UNIQUE INDEX  "AUTHORS_PK" ON  "AUTHORS" ("A_ID")
/
CREATE UNIQUE INDEX  "MEMBERS_PK" ON  "MEMBERS" ("M_ID")
/
CREATE UNIQUE INDEX  "GENRES_PK" ON  "GENRES" ("G_ID")
/
CREATE UNIQUE INDEX  "COPIES_PK" ON  "BOOK_COPIES" ("COPY_ID")
/
CREATE UNIQUE INDEX  "AR_PK" ON  "AUTHOR_REVIEWS" ("A_ID", "M_ID")
/
CREATE UNIQUE INDEX  "BR_PK" ON  "BOOK_REVIEWS" ("BK_ID", "M_ID")
/
CREATE UNIQUE INDEX  "BG_PK" ON  "BOOK_GENRES" ("BK_ID", "G_ID")
/
CREATE UNIQUE INDEX  "AG_PK" ON  "AUTHOR_GENRES" ("A_ID", "G_ID")
/
CREATE UNIQUE INDEX  "MP_PK" ON  "MEMBER_PREFERENCES" ("M_ID", "G_ID")
/
CREATE UNIQUE INDEX  "BOOK_COPIES_ISSUES_PK" ON  "BOOK_COPIES_ISSUES" ("ISSUE_ID", "COPY_ID", "M_ID")
/
CREATE UNIQUE INDEX  "BAP_PK" ON  "BOOK_AUTHOR_PUBLISHES" ("BK_ID", "A_ID")
/
CREATE UNIQUE INDEX  "UNIQUE_G_NAME" ON  "GENRES" ("G_NAME")
/
 CREATE SEQUENCE   "BOOKS_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL
/
 CREATE SEQUENCE   "AUTHORS_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL
/
 CREATE SEQUENCE   "MEMBERS_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 141 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL
/
 CREATE SEQUENCE   "COPIES_SEQUENCE"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL
/
 CREATE SEQUENCE   "ISSUES_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 221 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL
/
 CREATE SEQUENCE   "GENRES_SEQUENCE"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL
/
CREATE OR REPLACE EDITIONABLE TRIGGER  "AUTO_INC_BK_ID_ON_INSERT" 
  BEFORE INSERT ON books
  FOR EACH ROW
BEGIN
  SELECT books_sequence.nextval
  INTO :new.bk_id
  FROM dual;
END;

/
ALTER TRIGGER  "AUTO_INC_BK_ID_ON_INSERT" ENABLE
/
CREATE OR REPLACE EDITIONABLE TRIGGER  "AUTO_INC_A_ID_ON_INSERT" 
  BEFORE INSERT ON authors
  FOR EACH ROW
BEGIN
  SELECT authors_sequence.nextval
  INTO :new.a_id
  FROM dual;
END;

/
ALTER TRIGGER  "AUTO_INC_A_ID_ON_INSERT" ENABLE
/
CREATE OR REPLACE EDITIONABLE TRIGGER  "AUTO_INC_G_ID_ON_INSERT" 
  BEFORE INSERT ON genres
  FOR EACH ROW
BEGIN
  SELECT genres_sequence.nextval
  INTO :new.g_id
  FROM dual;
END;

/
ALTER TRIGGER  "AUTO_INC_G_ID_ON_INSERT" ENABLE
/
CREATE OR REPLACE EDITIONABLE TRIGGER  "AUTO_INC_M_ID_ON_INSERT" 
  BEFORE INSERT ON members
  FOR EACH ROW
BEGIN
  SELECT members_sequence.nextval
  INTO :new.m_id
  FROM dual;
END;

/
ALTER TRIGGER  "AUTO_INC_M_ID_ON_INSERT" ENABLE
/
CREATE OR REPLACE EDITIONABLE TRIGGER  "AUTO_INC_ISSUE_ID_ON_INSERT" 
  BEFORE INSERT ON book_copies_issues
  FOR EACH ROW
BEGIN
  SELECT issues_sequence.nextval
  INTO :new.issue_id
  FROM dual;
END;

/
ALTER TRIGGER  "AUTO_INC_ISSUE_ID_ON_INSERT" ENABLE
/
CREATE OR REPLACE EDITIONABLE TRIGGER  "AUTO_INC_COPY_ID_ON_INSERT" 
  BEFORE INSERT ON book_copies
  FOR EACH ROW
BEGIN
  SELECT copies_sequence.nextval
  INTO :new.copy_id
  FROM dual;
END;

/
ALTER TRIGGER  "AUTO_INC_COPY_ID_ON_INSERT" ENABLE
/
